### ISSUE TITLE
AttributeError when modifying landcover array to bool

### ISSUE THREAD

**Issue by C4K3** [chrieke/prettymapp#68]
Very minor issue that simply required me to set it to an empty array instead of False, it was just a little confusing because this use-case is in the documentation.

Setting
```
custom_lc_classes["urban"]["building"] = False
```
(as in the documentation) does work but setting
```
custom_lc_classes["urban"]["landuse"] = False
```
leads to
```
Traceback (most recent call last):
  File "/mnt/map.py", line 19, in <module>
    df = get_osm_geometries(aoi=aoi, landcover_classes=custom_lc_classes)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prettymapp/osm.py", line 83, in get_osm_geometries
    tags = get_osm_tags(landcover_classes=landcover_classes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prettymapp/osm.py", line 27, in get_osm_tags
    tags.setdefault(k, []).extend(v)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'extend'
```

**Comment by chrieke** [comment]
Nice! Thanks for reporting, fixed in https://github.com/chrieke/prettymapp/pull/71
